### ISSUE TITLE
Can't select GPIO pin between 0-9

### ISSUE THREAD

**Issue by me-henk** [botamochi6277/ros2_pigpio#3]
I have the issue that when selecting a GPIO pin number between 0 to 9 an error will be given, selecting a GPIO from 10 and up goes without error and works. I only tested this on the write and read, not on PWM and wheels.

I tried to enter the number in two ways, for example I'll use GPIO7:
ros2 run ros2_pigpio gpio_writer --ros-args --param pin:=7
ros2 run ros2_pigpio gpio_writer --ros-args --param pin:=07
ros2 run ros2_pigpio gpio_reader --ros-args --param pin:=7 --param is_pull_up:=false
ros2 run ros2_pigpio gpio_reader --ros-args --param pin:=07 --param is_pull_up:=false

Both give the same error for the write (the text is not fully correct, please check the image):
[INFO] [1723736005.741199014] [gpio_subscriber]: Write GPIO-07
terminate called after throwing an instance of 'rclcpp::exceptions::InvalidTopicNameError'
  what():  Invalid topic name: topic name must not contain characters other than alphanumerics, '_', '~', '{', or '}':
  'gpio_output_ 7'
                        ^

[ros2run]: Aborted

Also both give the same error for the read (the text is not fully correct, please check the image):
[INFO] [1723736147.921912773] [gpio_publisher]: Read GPIO-07 (PULL_DOWN)
terminate called after throwing an instance of 'rclcpp::exceptions::InvalidTopicNameError'
  what():  Invalid topic name: topic name must not contain characters other than alphanumerics, '_', '~', '{', or '}':
  'gpio_input_ 7'
                      ^

[ros2run]: Aborted

I am using Ubuntu 22.04 server and ros2 Humble, because github removes some of the underscores in my text and puts the ^ in the wrong place I added an image from the error messages were the underscore can be seen.
![github pigpio errors](https://github.com/user-attachments/assets/56274536-3ba6-4efd-bfb1-7933748d42d0)

**Comment by botamochi6277** [comment]
Hello me-henk, thank you for using this repository and sharing the issue. 👍 
This problem is due to wrong topic name making. 
I fixed it at [15bad4e96e417900cf2b3a697902e78abe0328dd](https://github.com/botamochi6277/ros2_pigpio/commit/15bad4e96e417900cf2b3a697902e78abe0328dd).
Please pull this commit and retry to use.

---
wrong points: 
before:
```cpp
ss << "gpio_input_" << std::setw(2) << pin_;
```
after:
```cpp
ss << "gpio_input_" << std::setfill('0') << std::right << std::setw(2) << pin_;
```

**Comment by me-henk** [comment]
Thank you for the fast response and fix.
I just did a test with the new fix and all is working now.

**Comment by me-henk** [comment]
Thank you for the fast response and fix.
I just did a test with the new fix and all is working now.
